fix: QWeb template percent sign formatting error
Fixed 'incomplete format' error in NAID operator certification report
- Changed: '%.1f%%' % doc.training_progress (incorrect - double %)
- To: '%.1f' % doc.training_progress followed by literal %
- QWeb templates require % sign outside of Python string formatting

Error: ValueError: incomplete format
Template: records_management.report_naid_operator_certification_view